name: Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install packages required for the build
      run: |
        DEBIAN_FRONTEND=noninteractive  apt -qq -y install -qq devscripts equivs
        mk-build-deps -i -s sudo -t "apt --yes --no-install-recommends"
        
    - name: build the hello-qt5 package
      run: dpkg-buildpackage -b -rfakeroot -us -uc
      
    - name: install the hello-qt5 package
      run: dpkg -i ../hello-qt5*deb
