name: Release tags

on:
  push:
    tags:
      - "v*" # matches v1.0.1, v1.2, v2, etc

jobs:
  buildLinux:
    name: Build ${{ matrix.ubuntu }}
    needs: once
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          submodules: false

      - name: install packages required for the build
        run: |
          sudo apt update
          sudo apt full-upgrade -y
          sudo DEBIAN_FRONTEND=noninteractive apt -qq -y install devscripts equivs
          mk-build-deps -i -s sudo -t "apt --yes --no-install-recommends"

      - name: build deb package
        run: dpkg-buildpackage -b -rfakeroot -us -uc
        
      - name: Upload deb package to release
        needs: [buildLinux]
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ../*.deb
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
